### ISSUE TITLE
 Only PCB V1 is included

### ISSUE THREAD

**Issue by Bruur-vr** [retrobuiltRyan/MacroKeyboardV2#1]
First time actually using Github:

After opening .brd & .sch files they are for v1 (2 row 4 column). Would it be possible to upload V2?

**Comment by retrobuiltRyan** [comment]
oops.
Im in the git right now, removing the outdated, uploading the correct.
thank you! be ready in 10min i think

**Comment by retrobuiltRyan** [comment]
fixed.

**Comment by retrobuiltRyan** [comment]
also removing v1.0
